#!/bin/bash
#SBATCH -J serial          	# job name
#SBATCH -o serial.%j.out       	# output and error file name (%j expands to jobID)
#SBATCH -n 1             	# total number of mpi tasks requested
#SBATCH -p gpu     		# queue (partition) -- can use gpu or gpudev
#SBATCH -t 00:10:00        	# run time (hh:mm:ss) - 10 minutes

ibrun ./serial -n 2000 -o serial.txt             
./autocorrect -s serial.txt
